### PR TITLE
Do not pass os.Stdin to launched command

### PR DESCRIPTION
**Pull request by bockstaller**
This is related to https://github.com/getgauge/gauge/issues/2419
- removes problematic line
- references issue in the code
- updates the dependencies in order to get go build and go test working

Signed-off by: Lukas Bockstaller <lukas.bockstaller@posteo.de>

### CODE REVIEW

**Comment by bockstaller** [comment]
I am still testing locally to make sure that this fixes the issue for good

**Comment by bockstaller** [comment]
I was able to verify that `gauge-ts` is working with this version. `gauge-python` continues to work. But I wasn't able to get a ruby project of the ground and running in order to test `gauge-ruby` (but that is a ruby and not a gauge-ruby problem)

**Comment by chadlwilson** [comment]
@bockstaller I'll take a look at gauge-ruby to sanity test it, as it's in active use for [gocd](https://github.com/gocd/gocd) so I've been maintaining it recently. I was about to bump the golang build version so can bump gauge-common also. Should be fine.

**Review by chadlwilson — APPROVED** [review]

**Comment by chadlwilson** [comment]
Rebased off master to separate the fix here from the dependency clean-up.

**Pull request merged**
